version: "3"

services:
  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - swimlane-practical-net
  web:
    build: .
    environment:
      MONGODB_URL: mongodb://mongodb:27017/database
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - swimlane-practical-net

networks:
  swimlane-practical-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local